# Generated by Django 5.0 on 2024-04-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movierecommendation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierecommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
