# Generated by Django 5.0 on 2024-04-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_movierecommendation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
